% Establish_Global.m

global alpha_out
global radius
global distance
global distance_total
global tire_coeff_lat
global tire_coeff_lon
global mulat
global mulon
global alpha
global m
global track
global l
global cg_h
global wdf
global rdf
global a
global b
global c_lift
global c_drag
global drs
global accel_tol
global time
global dt
global roundoff
global v_range
global Engine
global finaldrive
global enduro_laps
global tbest
global SA_max
global SR_max
global SA_res
global SR_res
global SA_range
global drive_out
global brake_out
global v_max
global fuel
global gear_pos
global skidpadtime
global fuel_flow
global rpm_limit
